theme = "rose_pine_moon"

[editor]
auto-format = false
cursorline  = true
line-number = "relative"
true-color  = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.statusline.mode]
normal = "N"
insert = "I"
select = "S"

[editor.soft-wrap]
enable = true
[keys.normal."space".i]
"+" = ":sh echo %{buffer_name}:%{cursor_line} | pbcopy"
