dictionaries = [
    "en_gb",
    "en_us",
    "ru",
]
words = [
    "chmod",
    "customisations",
    "gitlab",
    "traefik",
    "акторы",
    "баги",
    "валидации",
    "валидировать",
    "валидируется",
    "валидируются",
    "деплой",
    "деплою",
    "инициализируются",
    "конфдаты",
    "конфиг",
    "конфига",
    "конфиги",
    "конфигов",
    "линтера",
    "логирования",
    "мессенджер",
    "микросервис",
    "невалидны",
    "оркестрирующий",
    "пайплайна",
    "пайплайне",
    "пересобирает",
    "проксирующий",
    "репозитории",
    "репозиторий",
    "репозитория",
    "роутер",
    "сервисами",
    "сервисов",
    "сервисы",
    "склонировать",
    "сущностями",
    "токен",
    "токена",
    "форматтеры",
    "фреймворк",
    "чаты",
]
