gui:
  filterMode: 'fuzzy'
  nerdFontsVersion: '3'
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
